### ISSUE TITLE
StripeInvalidRequestError: Invalid integer: 3845.0000000000005

### ISSUE THREAD

**Issue by calumbradley** [calumbradley/cakeitorleaveit#6]
StripeInvalidRequestError: Invalid integer: 3845.0000000000005
    at Function.generate (/Users/calumbradley/Development/cakeitorleaveit/cakeitorleaveit/server/node_modules/stripe/lib/Error.js:40:16)
    at res.toJSON.then.StripeAPIError.message (/Users/calumbradley/Development/cakeitorleaveit/cakeitorleaveit/server/node_modules/stripe/lib/StripeResource.js:220:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'StripeInvalidRequestError',
  raw: {
    code: 'parameter_invalid_integer',
    doc_url: 'https://stripe.com/docs/error-codes/parameter-invalid-integer',
    message: 'Invalid integer: 3845.0000000000005',
    param: 'line_items[0][price_data][unit_amount]',
    type: 'invalid_request_error',
    headers: {
      server: 'nginx',
      date: 'Thu, 30 Dec 2021 22:00:10 GMT',
      'content-type': 'application/json',
      'content-length': '287',
      connection: 'keep-alive',
      'access-control-allow-credentials': 'true',
      'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
      'access-control-max-age': '300',
      'cache-control': 'no-cache, no-store',
      'idempotency-key': '949bc9c7-927a-4ef8-877b-8ecc237f89aa',
      'original-request': 'req_pVTShiKe9D63yY',
      'request-id': 'req_pVTShiKe9D63yY',
      'stripe-version': '2020-08-27',
      'strict-transport-security': 'max-age=31556926; includeSubDomains; preload'
    },
    statusCode: 400,
    requestId: 'req_pVTShiKe9D63yY'
  },
  rawType: 'invalid_request_error',
  code: 'parameter_invalid_integer',
  doc_url: 'https://stripe.com/docs/error-codes/parameter-invalid-integer',
  param: 'line_items[0][price_data][unit_amount]',
  detail: undefined,
  headers: {
    server: 'nginx',
    date: 'Thu, 30 Dec 2021 22:00:10 GMT',
    'content-type': 'application/json',
    'content-length': '287',
    connection: 'keep-alive',
    'access-control-allow-credentials': 'true',
    'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
    'access-control-max-age': '300',
    'cache-control': 'no-cache, no-store',
    'idempotency-key': '949bc9c7-927a-4ef8-877b-8ecc237f89aa',
    'original-request': 'req_pVTShiKe9D63yY',
    'request-id': 'req_pVTShiKe9D63yY',
    'stripe-version': '2020-08-27',
    'strict-transport-security': 'max-age=31556926; includeSubDomains; preload'
  },
  requestId: 'req_pVTShiKe9D63yY',
  statusCode: 400,
  charge: undefined,
  decline_code: undefined,
  payment_intent: undefined,
  payment_method: undefined,
  payment_method_type: undefined,
  setup_intent: undefined,
  source: undefined
}

**Comment by calumbradley** [comment]
see 0886820a95b6a9cf469a974650e507e6953b02d9 

https://github.com/calumbradley/cakeitorleaveit/commit/0886820a95b6a9cf469a974650e507e6953b02d9
